/*
 * generated by Xtext 2.35.0
 */
package org.example.cds.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class CDSUiModule extends AbstractCDSUiModule {

	public CDSUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
