/*
 * generated by Xtext 2.35.0
 */
package org.example.cds;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class CDSStandaloneSetup extends CDSStandaloneSetupGenerated {

	public static void doSetup() {
		new CDSStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
