/*
 * generated by Xtext 2.35.0
 */
package org.example.cds.formatting2;

import org.eclipse.xtext.formatting2.AbstractJavaFormatter;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.example.cds.cDS.Annotation;
import org.example.cds.cDS.CdsFile;
import org.example.cds.cDS.Definition;
import org.example.cds.cDS.Element;
import org.example.cds.cDS.EntityDef;
import org.example.cds.cDS.UsingDecl;

public class CDSFormatter extends AbstractJavaFormatter {

	protected void format(CdsFile cdsFile, IFormattableDocument doc) {
		// TODO: format HiddenRegions around keywords, attributes, cross references, etc. 
		doc.format(cdsFile.getNamespaceDecl());
		for (UsingDecl usingDecl : cdsFile.getImports()) {
			doc.format(usingDecl);
		}
		for (Definition definition : cdsFile.getDefinitions()) {
			doc.format(definition);
		}
	}

	protected void format(EntityDef entityDef, IFormattableDocument doc) {
		// TODO: format HiddenRegions around keywords, attributes, cross references, etc.
		for (Annotation _annotation : entityDef.getAnnotations()) {
			doc.format(_annotation);
		}
		// EntityDef.members contains Elements, ActionDef, and FunctionDef
		for (Object member : entityDef.getMembers()) {
			if (member instanceof Element) {
				doc.format(member);
			}
		}
	}
	
	// TODO: implement for TypeDef, AspectDef, ServiceDef, ServiceEntity, ExtendDef, AnnotateDef, Element, AssocDef, TypeRef, Annotation, ArrayAnnotationValue, RecordAnnotationValue, RecordEntry, BinaryExpr, UnaryExpr, LiteralExpr, FuncExpr
}
