/*
 * generated by Xtext 2.35.0
 */
package org.example.cds.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.example.cds.CDSRuntimeModule;
import org.example.cds.CDSStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class CDSIdeSetup extends CDSStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new CDSRuntimeModule(), new CDSIdeModule()));
	}
	
}
